/** biome-ignore-all lint/suspicious/noExplicitAny: REASON */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

export const Index: Record<string, any> = {

  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/lib/utils.ts")),
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/ui/button.tsx")),
    files: [{
      path: "registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "checkbox": {
    name: "checkbox",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/ui/checkbox.tsx")),
    files: [{
      path: "registry/ui/checkbox.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/ui/dropdown-menu.tsx")),
    files: [{
      path: "registry/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field": {
    name: "field",
    description: "",
    type: "registry:ui",
    registryDependencies: ["label","separator"],
    component: lazy(() => import("~/registry/v1/ui/field.tsx")),
    files: [{
      path: "registry/ui/field.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "select": {
    name: "select",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/ui/select.tsx")),
    files: [{
      path: "registry/ui/select.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/hooks/use-mobile.ts")),
    files: [{
      path: "registry/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-default": {
    name: "button-default",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-default.tsx")),
    files: [{
      path: "registry/examples/button-default.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-demo.tsx")),
    files: [{
      path: "registry/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-destructive": {
    name: "button-destructive",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-destructive.tsx")),
    files: [{
      path: "registry/examples/button-destructive.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-ghost": {
    name: "button-ghost",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-ghost.tsx")),
    files: [{
      path: "registry/examples/button-ghost.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-icon": {
    name: "button-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-icon.tsx")),
    files: [{
      path: "registry/examples/button-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-link": {
    name: "button-link",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-link.tsx")),
    files: [{
      path: "registry/examples/button-link.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-loading": {
    name: "button-loading",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","spinner"],
    component: lazy(() => import("~/registry/v1/examples/button-loading.tsx")),
    files: [{
      path: "registry/examples/button-loading.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-outline": {
    name: "button-outline",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-outline.tsx")),
    files: [{
      path: "registry/examples/button-outline.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-rounded": {
    name: "button-rounded",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-rounded.tsx")),
    files: [{
      path: "registry/examples/button-rounded.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-secondary": {
    name: "button-secondary",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-secondary.tsx")),
    files: [{
      path: "registry/examples/button-secondary.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-sizes": {
    name: "button-sizes",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-sizes.tsx")),
    files: [{
      path: "registry/examples/button-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-with-icon": {
    name: "button-with-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-with-icon.tsx")),
    files: [{
      path: "registry/examples/button-with-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-checkboxes": {
    name: "dropdown-menu-checkboxes",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/v1/examples/dropdown-menu-checkboxes.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-checkboxes.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/v1/examples/dropdown-menu-demo.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-dialog": {
    name: "dropdown-menu-dialog",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/v1/examples/dropdown-menu-dialog.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-dialog.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu-radio-group": {
    name: "dropdown-menu-radio-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    component: lazy(() => import("~/registry/v1/examples/dropdown-menu-radio-group.tsx")),
    files: [{
      path: "registry/examples/dropdown-menu-radio-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-demo": {
    name: "field-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["field"],
    component: lazy(() => import("~/registry/v1/examples/field-demo.tsx")),
    files: [{
      path: "registry/examples/field-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "select-demo": {
    name: "select-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["select"],
    component: lazy(() => import("~/registry/v1/examples/select-demo.tsx")),
    files: [{
      path: "registry/examples/select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    component: lazy(() => import("~/registry/v1/examples/tooltip-demo.tsx")),
    files: [{
      path: "registry/examples/tooltip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
}
