/** biome-ignore-all lint/suspicious/noExplicitAny: REASON */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

export const Index: Record<string, any> = {

  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/lib/utils.ts")),
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/ui/button.tsx")),
    files: [{
      path: "registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "checkbox": {
    name: "checkbox",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/ui/checkbox.tsx")),
    files: [{
      path: "registry/ui/checkbox.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/v1/hooks/use-mobile.ts")),
    files: [{
      path: "registry/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/v1/examples/button-demo.tsx")),
    files: [{
      path: "registry/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    component: lazy(() => import("~/registry/v1/examples/checkbox-demo.tsx")),
    files: [{
      path: "registry/examples/checkbox-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    component: lazy(() => import("~/registry/v1/examples/tooltip-demo.tsx")),
    files: [{
      path: "registry/examples/tooltip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
}
